shopware:
    auto_update:
        # Disables the auto updater in the UI
        enabled: false
    admin_worker:
        enable_admin_worker: false
        
# The Admin worker should be disabled on production server.
# enable_admin_worker: false
